// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqJoeDWUswlNc5eeR-hbna5OeigL12uJE',
    appId: '1:1051650789426:web:2f2c5575207b4512022c2b',
    messagingSenderId: '1051650789426',
    projectId: 'firstapp-d9d53',
    authDomain: 'firstapp-d9d53.firebaseapp.com',
    databaseURL: 'https://firstapp-d9d53-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firstapp-d9d53.firebasestorage.app',
    measurementId: 'G-49BE8DS2PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDodibhx1i8nXDSwz-q_HJKROUY1cRzi44',
    appId: '1:1051650789426:android:441212bee2f5a19a022c2b',
    messagingSenderId: '1051650789426',
    projectId: 'firstapp-d9d53',
    databaseURL: 'https://firstapp-d9d53-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firstapp-d9d53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDhIbHuFCeTAsIh4ViiVpNCh97TnboIic',
    appId: '1:1051650789426:ios:ff2f1011d0142efb022c2b',
    messagingSenderId: '1051650789426',
    projectId: 'firstapp-d9d53',
    databaseURL: 'https://firstapp-d9d53-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firstapp-d9d53.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDhIbHuFCeTAsIh4ViiVpNCh97TnboIic',
    appId: '1:1051650789426:ios:ff2f1011d0142efb022c2b',
    messagingSenderId: '1051650789426',
    projectId: 'firstapp-d9d53',
    databaseURL: 'https://firstapp-d9d53-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firstapp-d9d53.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqJoeDWUswlNc5eeR-hbna5OeigL12uJE',
    appId: '1:1051650789426:web:ef9611343733578b022c2b',
    messagingSenderId: '1051650789426',
    projectId: 'firstapp-d9d53',
    authDomain: 'firstapp-d9d53.firebaseapp.com',
    databaseURL: 'https://firstapp-d9d53-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firstapp-d9d53.firebasestorage.app',
    measurementId: 'G-H59XHENT5K',
  );

}