// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8ftp-aciwe326K_vTxbFUabrcOlfPAnY',
    appId: '1:789941840187:web:93bddca74698da1e766f1e',
    messagingSenderId: '789941840187',
    projectId: 'belajar-4c14e',
    authDomain: 'belajar-4c14e.firebaseapp.com',
    databaseURL: 'https://belajar-4c14e-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-4c14e.firebasestorage.app',
    measurementId: 'G-YPCJK58YBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDGhnY_g_gNjnv1YaRLHVBil0avOrMYSs',
    appId: '1:789941840187:android:f929cf4f45aa6090766f1e',
    messagingSenderId: '789941840187',
    projectId: 'belajar-4c14e',
    databaseURL: 'https://belajar-4c14e-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-4c14e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP0NNSjCiusRnphmQ_RTiyYLgkv3bhjjM',
    appId: '1:789941840187:ios:2b0ed386b29b1faa766f1e',
    messagingSenderId: '789941840187',
    projectId: 'belajar-4c14e',
    databaseURL: 'https://belajar-4c14e-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-4c14e.firebasestorage.app',
    iosBundleId: 'com.example.utsbelajar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP0NNSjCiusRnphmQ_RTiyYLgkv3bhjjM',
    appId: '1:789941840187:ios:2b0ed386b29b1faa766f1e',
    messagingSenderId: '789941840187',
    projectId: 'belajar-4c14e',
    databaseURL: 'https://belajar-4c14e-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-4c14e.firebasestorage.app',
    iosBundleId: 'com.example.utsbelajar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8ftp-aciwe326K_vTxbFUabrcOlfPAnY',
    appId: '1:789941840187:web:008c680234e1767e766f1e',
    messagingSenderId: '789941840187',
    projectId: 'belajar-4c14e',
    authDomain: 'belajar-4c14e.firebaseapp.com',
    databaseURL: 'https://belajar-4c14e-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-4c14e.firebasestorage.app',
    measurementId: 'G-H5H4HBNDWL',
  );

}